@echo off
setlocal enabledelayedexpansion

echo.
echo =============================================
echo Prisma Migration Baseline Reset Script
echo =============================================
echo.

REM Check Node.js
echo Checking Node.js...
where node >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Node.js not found
    pause
    exit /b 1
)
echo [OK] Node.js found

REM Check npx
echo Checking npx...
where npx >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] npx not found
    pause
    exit /b 1
)
echo [OK] npx found

REM Confirm
echo.
echo WARNING: This will clear local migration history and create new baseline.
set /p confirm=Continue? (y/N): 
if /i not "!confirm!"=="y" (
    echo [CANCELLED]
    pause
    exit /b 0
)

echo.
echo 1/6. Backup database...
REM Use wmic to get consistent timestamp format
for /f "tokens=2 delims==" %%a in ('wmic OS Get localdatetime /value') do set "backup_dt=%%a"
set "backup_timestamp=%backup_dt:~0,8%_%backup_dt:~8,6%"
set "backup_file=milicard_dev_backup_%backup_timestamp%.sql"
echo Backup file: %backup_file%
set PGPASSWORD=840928
pg_dump -h localhost -p 5437 -d milicard_dev -U postgres > "%backup_file%" 2>nul
if errorlevel 1 (
    echo [WARN] Backup failed (may need password or connection issue)
    echo        Continuing anyway...
) else (
    echo [OK] Database backed up to %backup_file%
)

echo.
echo 2/6. Pull schema from database...
REM Use db pull to ensure schema.prisma reflects actual database state
call npx prisma db pull
if %errorlevel% neq 0 (
    echo [ERROR] prisma db pull failed
    pause
    exit /b 1
)
echo [OK] schema.prisma synced from database

echo.
echo 3/6. Clear local migrations directory...
if exist prisma\migrations (
    rd /s /q prisma\migrations
    if errorlevel 1 (
        echo [ERROR] Cannot delete prisma\migrations directory
        pause
        exit /b 1
    )
)
mkdir prisma\migrations >nul 2>&1

echo.
echo 4/6. Generate initial migration SQL...
set temp_migration_dir=prisma\migrations\temp_migration
mkdir "!temp_migration_dir!" >nul 2>&1

REM Generate migration SQL
call npx prisma migrate diff --from-empty --to-schema-datamodel prisma\schema.prisma --script > "!temp_migration_dir!\migration.sql"
if errorlevel 1 (
    echo [ERROR] Failed to generate migration SQL
    pause
    exit /b 1
)

REM Create timestamp directory
for /f "tokens=2 delims==" %%a in ('wmic OS Get localdatetime /value') do set "dt=%%a"
set "YY=%dt:~2,2%" & set "YYYY=%dt:~0,4%" & set "MM=%dt:~4,2%" & set "DD=%dt:~6,2%" & set "HH=%dt:~8,2%" & set "Min=%dt:~10,2%" & set "Sec=%dt:~12,2%"
set timestamp=!YYYY!!MM!!DD!!HH!!Min!!Sec!

set init_migration_dir=prisma\migrations\!timestamp!_init_from_db
mkdir "!init_migration_dir!" >nul 2>&1

copy "!temp_migration_dir!\migration.sql" "!init_migration_dir!\migration.sql" >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Failed to copy migration file
    pause
    exit /b 1
)

REM Create migration_lock.toml
(
echo # Please do not edit this file manually
echo # It should be added in your version-control system (i.e. Git)
echo provider = "postgresql"
) > "prisma\migrations\migration_lock.toml"

REM Clean temp directory
rd /s /q "!temp_migration_dir!"

echo.
echo 5/6. Clear _prisma_migrations table...
set PGPASSWORD=840928
psql -h localhost -p 5437 -d milicard_dev -U postgres -c "DELETE FROM _prisma_migrations;" 2>nul
if errorlevel 1 (
    echo [WARN] Failed to clear _prisma_migrations table
    echo        Please run manually: DELETE FROM _prisma_migrations;
)

echo.
echo 6/6. Mark initial migration as applied...
set migration_name=!timestamp!_init_from_db
call npx prisma migrate resolve --applied "!migration_name!"
if errorlevel 1 (
    echo [ERROR] Failed to mark migration as applied
    pause
    exit /b 1
)

echo.
echo =============================================
echo [SUCCESS] Operation completed!
echo.
echo - Local migrations directory rebuilt
echo - Database structure synced with schema.prisma
echo - Database data preserved
echo - You can now use: npx prisma migrate dev
echo =============================================
echo.
echo Generated migration: !init_migration_dir!
echo Migration marked as applied: !migration_name!
echo.

pause